services:
  - type: web
    name: social-media-app
    env: node
    plan: free
    buildCommand: |
      chmod +x frontend/build.sh
      cd frontend
      ./build.sh
      cd ../backend
      npm install
    startCommand: cd backend && npm start
    runtime: node
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://social-media-cs6p.onrender.com

  - type: web
    name: social-media-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com # Replace with your backend URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 